
language: php

# only build master branch (and PRs)
branches:
  only:
    - "master"

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  
env:
  - PHPUNIT=true

os: linux

matrix:
  include:
      # add tests without coverage
      # add extra test runs for php7: coverage, codestyle
    - php: 7.0
      env: CODE_STYLE=true
    - php: 8.0
      env: CODE_STYLE=true

install:
    - composer update

before_script:
  - if [ "${COVERAGE}" != "true" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then phpenv config-rm xdebug.ini && echo "xdebug disabled"; fi

script:
  - if [ "$PHPUNIT" = "true" ]; then vendor/bin/phpunit; fi
  - if [ "$CODE_STYLE" = "true" ]; then vendor/bin/phpcs -n --standard=PSR1,PSR2 src test && echo "Code style OK"; fi

after_script:
  - if [ "${COVERAGE}" = "true" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/coverage.clover; fi
